# Generated by Django 5.1.7 on 2025-03-18 04:36

import django.db.models.deletion
import reminder.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assistant_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('model', models.CharField(default='gpt-4-mini', max_length=50)),
                ('instructions', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BatchTimeout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_timeout_seconds', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(max_length=255, unique=True, verbose_name='OpenAI Run ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('in_progress', 'In Progress'), ('requires_action', 'Requires Action'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='queued', max_length=20, verbose_name='Run Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Timestamp')),
                ('run_expired_at', models.DateTimeField(blank=True, null=True, verbose_name='Run Expiration Timestamp')),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_id', models.CharField(default=reminder.models.generate_uuid, editable=False, max_length=120, unique=True)),
                ('order_key', models.CharField(default=reminder.models.generate_uuid, editable=False, max_length=120, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=reminder.models.calculate_expiry)),
                ('assistant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='threads', to='reminder.assistant')),
                ('current_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_thread', to='reminder.run')),
            ],
        ),
    ]
