# Generated by Django 5.1.7 on 2025-03-18 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0002_assistant_batchtimeout_run_thread'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='appointment_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
