# Generated by Django 5.1.7 on 2025-03-28 05:15

import reminder.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0003_thread_appointment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='order_key',
            field=models.CharField(default=reminder.models.generate_uuid, editable=False, max_length=120),
        ),
    ]
