# Generated by Django 5.1.7 on 2025-03-28 05:16

import reminder.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0004_alter_thread_order_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='thread_id',
            field=models.CharField(default=reminder.models.generate_uuid, editable=False, max_length=120),
        ),
    ]
