# Generated by Django 5.1.7 on 2025-03-31 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0005_alter_thread_thread_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата слота')),
                ('time', models.TimeField(verbose_name='Время слота')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='available_slots', to='reminder.clinic', verbose_name='Клиника')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='available_slots', to='reminder.doctor', verbose_name='Врач')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_slots', to='reminder.patient', verbose_name='Пациент')),
            ],
            options={
                'verbose_name': 'Доступный временной слот',
                'verbose_name_plural': 'Доступные временные слоты',
                'ordering': ['date', 'time'],
                'unique_together': {('patient', 'date', 'time')},
            },
        ),
    ]
