# Generated by Django 5.1.7 on 2025-04-03 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0006_availabletimeslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='queueinfo',
            name='internal_reason_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Внутренний код причины'),
        ),
        migrations.AddField(
            model_name='queueinfo',
            name='internal_reason_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Внутреннее название причины'),
        ),
        migrations.CreateModel(
            name='QueueReasonMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_code', models.CharField(max_length=20, verbose_name='Внутренний код')),
                ('internal_name', models.CharField(max_length=255, verbose_name='Внутреннее название')),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='reminder.queuereason', verbose_name='Причина из Инфоклиники')),
            ],
            options={
                'verbose_name': 'Сопоставление причин',
                'verbose_name_plural': 'Сопоставления причин',
                'unique_together': {('reason', 'internal_code')},
            },
        ),
    ]
