# Generated by Django 5.1.7 on 2025-05-05 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0008_call_patient_code_call_queue_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='last_used_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reminder.doctor'),
        ),
        migrations.CreateModel(
            name='PatientDoctorAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reminder.department')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reminder.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_associations', to='reminder.patient')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('patient', 'doctor')},
            },
        ),
    ]
