# Generated by Django 5.1.7 on 2025-05-05 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0009_patient_last_used_doctor_patientdoctorassociation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientdoctorassociation',
            options={'ordering': ['-updated_at']},
        ),
        migrations.RemoveField(
            model_name='patientdoctorassociation',
            name='department',
        ),
        migrations.RemoveField(
            model_name='patientdoctorassociation',
            name='is_active',
        ),
        migrations.AddField(
            model_name='patientdoctorassociation',
            name='booking_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patientdoctorassociation',
            name='is_preferred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientdoctorassociation',
            name='last_booking_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientdoctorassociation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='patientdoctorassociation',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_associations', to='reminder.doctor'),
        ),
    ]
